version: '2'

services:
  mongo:
    container_name: mongo
    image: mongo:{{mongo.version}}
    hostname: mongo
    networks:
      - {{mongo.install}}
    volumes:
      - /opt/conf/{{mongo.install}}:/opt/conf
      - /mnt/data:/data
    ports:
      - "27017:27017"
      - "28017:28017"
    logging:
      driver: json-file
      options:
        max-file: "4"
        max-size: "25m"
    restart: unless-stopped
    command: mongod --config /opt/conf/mongo.conf

{{#if backup.enable}}
  backup:
    container_name: backup
    image: harlanj/mongo-cron-backup:0.1.1
    networks:
      - {{mongo.install}}
    environment:
      NODE_ENV: production
      MONGO_HOST: mongo:27017
      MONGO_USERNAME: {{mongo.username}}
      MONGO_PASSWORD: {{mongo.password}}
      MONGO_OPLOG: "true"
      MONGO_OUTPUT_DIR: /backup
      LOG_LEVEL: info
      CRON_SCHEDULE: 0 0,12 * * *
      AWS_S3_ACCESS_KEY: {{backup.s3AccessKey}}
      AWS_S3_SECRET_KEY: {{backup.s3SecretKey}}
      AWS_S3_BUCKET: {{backup.s3Bucket}}
    logging:
      driver: json-file
      options:
        max-file: "4"
        max-size: "25m"
    volumes:
      - /mnt/backup:/backup
    restart: unless-stopped
    depends_on:
      - mongo
{{/if}}

networks:
  {{mongo.install}}:
